audit_header: false
title: Pittsburgh Real Estate Video Blog with Matt Durbin
description: Our mission at Matt Durbin Real Estate Team is to be your best resource for Pittsburgh real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Matt Durbin Real Estate Team, your professional Pittsburgh Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Matt Durbin
  title:
  license_number:
  about_markdown: |
    The Matt Durbin Real Estate Team in Pittsburgh, PA is one of the top real estate teams in the area specializing in residential home listings and marketing.
  brand: Matt Durbin Real Estate Team
  brokerage: NextHome PPM Realty
  market: Pittsburgh
  address: 1308 Peermont Ave, Pittsburgh, PA 15216
  phone: 412-532-4686
  phone_type: Phone
  phone2: 412-343-6206
  phone2_type: Office
  email: TheMattDurbinTeam@ppmrealty.com
  url: http://MattDurbinRealEstate.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.ppmpropertysearch.com/ppm-realty-listings/?agent_id=4523
  second_CTA_text: Home Search
  second_CTA_URL: https://www.ppmpropertysearch.com/cma/property-valuation/?agent_id=4523

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Pittsburgh Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.ppmpropertysearch.com/ppm-realty-listings/?agent_id=4523

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Pittsburgh Home?"
    CTA_text2: "Search the entire MLS for your Pittsburgh home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.ppmpropertysearch.com/cma/property-valuation/?agent_id=4523

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/MattDurbinExpertAdvisor
  linkedin_url: https://www.linkedin.com/in/mattdurbinpa/
  youtube_url: https://www.youtube.com/channel/UCKEV7zoa_B4tYB56xoc5dOQ?view_as=subscriber
  twitter_url: https://twitter.com/MattDurbinTeam
  instagram_url: https://www.instagram.com/mattdurbinteam/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://podcasts.apple.com/us/podcast/pittsburgh-real-estate-podcast-with-matt-durbin/id1479577441

podcast:
  title: 'Pittsburgh Real Estate Podcast with Matt Durbin'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Pittsburgh Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Matt Durbin Real Estate Team - your professional Pittsburgh Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Pittsburgh, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Matt Durbin'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Pittsburgh Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#236A95'
  theme_color: '#959499'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
